core/urls.py
from django.urls import path
from . import views
from .views import Classes, Courses, Rooms, Students
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('classes/', Classes.as_view(),name="classes"),
    path('courses/', Courses.as_view(), name="courses"),
    path('deletecourses/<int:pk>/', views.DeleteCourse, name="deletecourses"),
    path('rooms/', Rooms.as_view(), name="rooms"),
    path('deleterooms/<int:pk>/', views.DeleteRoom, name="deleterooms"),
    path('students/', Students.as_view(), name="students"),
    path('accounts/login/',auth_views.LoginView.as_view(template_name="core/login.html"), name="login"),
    path('logout/',auth_views.LogoutView.as_view(next_page='/'),name='logout'),
    path('class/<int:pk>/', views.detail_class, name="detail_class"),
    path('register/', views.register , name='register'),
    path('profile/', views.Profiles , name='profile'),
    path('profile/update/', views.UpdateProfile , name='updateprofile'),

]

xeplich/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from typing import ClassVar
from django.db import models
from django.db.models.deletion import CASCADE
from django.contrib.auth.models import User

# Create your models here.

STATUS_ROOM_CHOICES = (
    ("W", "Working"),
    ('U', 'Upgrading'),
    ('B', 'Broken')
)

DURATION_CHOICES = (
    (3, '3 Weeks' ),
    (4, '4 Weeks' ),
    (5, '5 Weeks' ),
    (6, '6 Weeks' ),
)

SCHEDULE_CHOICES = (
    ("MWF", "Shift Mon Wed Fri"),
    ("TTS", "Shift Tue Thu Sat"),
    ("F", "Shift All Week"),
)

STATUS_CHOICES = (
    ('DONE', 'Đã hoàn thành'),
    ('DOING', 'Đang học'),
    ('CANCELED', 'Đã huỷ'),
    ('WAITING', 'Đang chờ'),
    ('LOCKED', 'Đã khoá lớp'),
)
  

class Room(models.Model):
    name = models.CharField(default="", max_length=50)
    capacity = models.IntegerField(default = 0)
    status = models.CharField(choices=STATUS_ROOM_CHOICES, max_length=1, default="W")

    def __str__(self):
        return self.name


class Course(models.Model):
    name = models.CharField(default='',max_length=255)
    duration = models.IntegerField(choices=DURATION_CHOICES, default=3)

    def __str__(self):
        return self.name


class Class(models.Model):
    slug = models.SlugField(max_length=30,default='')
    name = models.CharField(default='',max_length=255)
    number = models.IntegerField(default=0)
    number_student = models.IntegerField(default=0)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="courses")
    duration = models.IntegerField(default=0)
    day = models.CharField(choices=SCHEDULE_CHOICES, max_length=4) # buổi học
    status = models.CharField(choices=STATUS_CHOICES, max_length=8, default="WAITING")

    def __str__(self):
        return self.name
    

class Student(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name="users",blank=True, null=True )
    name = models.CharField(default='',max_length=255)
    birth = models.DateField(blank=True, null=True)
    phone = models.CharField(default='',null=True,blank=True,max_length=13)
    classes = models.ManyToManyField(Class, blank=True, null=True , related_name="students")

    def __str__(self):
        return self.name


class Week(models.Model):
    start = models.DateField(blank=True, null=True)
    end = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return str(self.start) + " / " + str(self.end)


class ClassRoom(models.Model):
    classID = models.ForeignKey(Class, on_delete=models.CASCADE)
    roomID = models.ForeignKey(Room, on_delete=models.CASCADE)
    weekID = models.ForeignKey(Week, on_delete=models.CASCADE)
    day = models.CharField(default="", null=True, blank=True, max_length=3)
    
    def __str__(self) -> str:
        return str(self.classID.name) + " / " + str(self.roomID.name)
    

core/forms.py
from django import forms
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from .models import Student

class RegistrationForm(forms.Form):
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='Tên')
    username = forms.CharField(label='Tài Khoản',max_length=30)
    password1 = forms.CharField(label='Mật khẩu', widget=forms.PasswordInput())
    password2 = forms.CharField(label='Nhập Lại Mật khẩu', widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1= self.cleaned_data['password1']    
            password2= self.cleaned_data['password2']    
            if password1 == password2 and password1 :
                return password2
        raise forms.ValidationError('Mật khẩu không hợp lệ!')

    def clean_username(self):
        username = self.cleaned_data["username"]
        if not re.search(r'^\w+$', username):
            raise forms.ValidationError("tên tk có ký tự đặt biệt!")
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist: 
            return username
        raise forms.ValidationError("tài khoản đã tồn tại")

    def save(self):
        user = User.objects.create_user(username=self.cleaned_data['username'], email =self.cleaned_data['email'], password=self.cleaned_data['password1'], first_name = self.cleaned_data['first_name'])
        print("tạo user thành công ")
        Student.objects.create(user = user,name = self.cleaned_data['first_name'], birth = "2021-01-01")
        print("tạo student thành công ")

core/views.py
from django.core import exceptions
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Class, Course, Room, Student, Week, ClassRoom
from django.views import View
import datetime
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.models import User
from .forms import RegistrationForm

# region Front handler

def towf(rms, cls):
    list_cac_th = []
    list_max = []
    try:
        for i in range(rms.count()):
            if rms[i].capacity >= cls[0].number:
                for j in range(rms.count()):
                    if rms[j].capacity >= cls[1].number:
                        list_cach = [
                            [i,cls[0].duration],
                            [j,cls[1].duration],
                        ]
                        tong = 0
                        max = 0
                        for o in range(rms.count()): # tính max tổng duration
                            for p in list_cach:
                                if o == p[0]:
                                    tong += p[1]
                            if max < tong:
                                max = tong
                            tong = 0
                        list_max.append(max)
                        list_cac_th.append([list_cach,max])
    except:
        print("lỗi towf()")
    return list_cac_th, list_max

def threef(rms, cls): # i j k l m
    list_cac_th = []
    list_max = []
    try:
        for i in range(rms.count()):
            if rms[i].capacity >= cls[0].number:
                for j in range(rms.count()):
                    if rms[j].capacity >= cls[1].number:
                        for k in range(rms.count()):
                            if rms[k].capacity >= cls[2].number:          
                                list_cach = [
                                    [i,cls[0].duration],
                                    [j,cls[1].duration],
                                    [k,cls[2].duration],
                                ]
                                tong = 0
                                max = 0
                                for o in range(rms.count()): # tính max tổng duration
                                    for p in list_cach:
                                        if o == p[0]:
                                            tong += p[1]
                                    if max < tong:
                                        max = tong
                                    tong = 0
                                list_max.append(max)
                                list_cac_th.append([list_cach,max])

    except:
        print("lỗi threef()")
    return list_cac_th, list_max

def fourf(rms, cls): # i j k l m
    list_cac_th = []
    list_max = []
    try:
        for i in range(rms.count()):
            if rms[i].capacity >= cls[0].number:
                for j in range(rms.count()):
                    if rms[j].capacity >= cls[1].number:
                        for k in range(rms.count()):
                            if rms[k].capacity >= cls[2].number:
                                for l in range(rms.count()):
                                    if rms[l].capacity >= cls[3].number:
                                        list_cach = [
                                            [i,cls[0].duration],
                                            [j,cls[1].duration],
                                            [k,cls[2].duration],
                                            [l,cls[3].duration],
                                        ]
                                        tong = 0
                                        max = 0
                                        for o in range(rms.count()): # tính max tổng duration
                                            for p in list_cach:
                                                if o == p[0]:
                                                    tong += p[1]
                                            if max < tong:
                                                max = tong
                                            tong = 0
                                        list_max.append(max)
                                        list_cac_th.append([list_cach,max])
    except:
        print("lỗi fourf()")
    return list_cac_th, list_max

def fivef(rms, cls): # i j k l m
    list_cac_th = []
    list_max = []
    try:
        for i in range(rms.count()):
            if rms[i].capacity >= cls[0].number:
                for j in range(rms.count()):
                    if rms[j].capacity >= cls[1].number:
                        for k in range(rms.count()):
                            if rms[k].capacity >= cls[2].number:
                                for l in range(rms.count()):
                                    if rms[l].capacity >= cls[3].number:
                                        for m in range(rms.count()):
                                            if rms[m].capacity >= cls[4].number:
                                                list_cach = [
                                                    [i,cls[0].duration],
                                                    [j,cls[1].duration],
                                                    [k,cls[2].duration],
                                                    [l,cls[3].duration],
                                                    [m,cls[4].duration],
                                                ]
                                                tong = 0
                                                max = 0
                                                for o in range(rms.count()): # tính max tổng duration
                                                    for p in list_cach:
                                                        if o == p[0]:
                                                            tong += p[1]
                                                    if max < tong:
                                                        max = tong
                                                    tong = 0
                                                list_max.append(max)
                                                list_cac_th.append([list_cach,max])
    except:
        print("lỗi fivef()")
    return list_cac_th, list_max

#list_cac_th, list_max
def sixf(rms, cls): # i j k l m
    list_cac_th = []
    list_max = []
    try:
        for i in range(rms.count()):
            if rms[i].capacity >= cls[0].number:
                for j in range(rms.count()):
                    if rms[j].capacity >= cls[1].number:
                        for k in range(rms.count()):
                            if rms[k].capacity >= cls[2].number:
                                for l in range(rms.count()):
                                    if rms[l].capacity >= cls[3].number:
                                        for m in range(rms.count()):
                                            if rms[m].capacity >= cls[4].number:
                                                for n in range(rms.count()):
                                                    if rms[n].capacity >= cls[4].number:

                                                        list_cach = [
                                                            [i,cls[0].duration],
                                                            [j,cls[1].duration],
                                                            [k,cls[2].duration],
                                                            [l,cls[3].duration],
                                                            [m,cls[4].duration],
                                                            [n,cls[5].duration],
                                                        ]
                                                        tong = 0
                                                        max = 0
                                                        for o in range(rms.count()): # tính max tổng duration
                                                            for p in list_cach:
                                                                if o == p[0]:
                                                                    tong += p[1]
                                                            if max < tong:
                                                                max = tong
                                                            tong = 0
                                                        list_max.append(max)
                                                        list_cac_th.append([list_cach,max])
    except:
        print("lỗi sixf()")
    return list_cac_th, list_max

def case(n, rms, cls):
    switcher = {
        2 : towf(rms, cls),
        3 : threef(rms, cls),
        4 : fourf(rms, cls),
        5 : fivef(rms, cls),
        6 : sixf(rms, cls)
    }
    return switcher.get(n,"nothing")

#for5 cũ
def xuly246357(rms, cls): # i j k l m
    result = case(cls.count(),rms,cls)
    list_cac_th = result[0]
    list_max = result[1]
    
    m = min(list_max)
    for i in list_cac_th:
        if i[1] == m:
            truong_hop_chon = i[0]
            print( "cach xep phong :",i[0])
            # tách ds index phòng
            list_index_room = []
            list_index_duration = []


            for j in range(len(i[0])):
                rm = rms[i[0][j][0]]
                cl =  cls[j]
                today = datetime.date.today() # .day.weekday() # thứ 2 -> cn = 0 -> 6
                dtt = datetime.timedelta(days= 7 * i[0][j][1] ) # delta time

                if list_index_room.count(i[0][j][0]) == 0:
                    list_index_room.append(i[0][j][0])

core/templates/core/class_view.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
Dashboard scheduling
{% endblock title %}

{% block head %}
<title>Class</title>
<link rel="stylesheet" href="{% static 'css/css/classes.css' %}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
{% endblock head %}

{% block contain %}

<div class="class-wrapper">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="text-center alert alert-{{ message.tags }} fade in alert-dismissible show"{% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" style="font-size:20px">&times;</span>
            </button>  
        {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <form name="formclass" action="" method="post">
        {% csrf_token %}
        <h2 class="qllh">classes management</h2>

        <div class="form-group">
            <label for="">Mã lớp</label>
            <input type="text" name="slug" required="" placeholder="Nhập mã lớp">
        </div>

        <div class="form-group">
            <label for="">Tên lớp</label>
            <input type="text" name="name" required="" placeholder="Nhập tên lớp">
        </div>

        <div class="form-group">
            <label for="">Số lượng</label>
            <input type="number" name="number" min="0" max="40" required="" placeholder="Nhập số lượng">
        </div>

        <div class="form-group">
            <label for="">Lịch học</label>
            <select name="schedule" id="schedule" required>
                <option disabled selected value>Chọn lịch học</option>
                <option value="MWF">Shift Mon Wed Fri</option>
                <option value="TTS">Shift Tue Thu Sat</option>
                <option value="F">Shift All Week</option>
            </select>
        </div>

        <div class="form-group">
            <label for="">Khoá học</label>
            <select name="courses" id="courses">
                <option disabled selected value>Chọn khóa học</option>

                {% for course in courses %}
                <option value="{{course.id}}">{{course.name}}</option>
                {% endfor %}
            </select>
        </div>

        <div class="form-submit">
            <input type="hidden" id="iId" name="iId">
            <input type="submit" name="add_class" value="Thêm">
            <input type="submit" name="update_class" value="Sửa">
            <input type="submit" name="delete_class" value="Xoá">
        </div>
    </form>

    <div class="view">
        <table class="custom-table">
            <tr class="tr-title">
                <th>Mã Lớp</th>
                <th>Tên Lớp</th>
                <th>Khoá học</th>
                <th>Sĩ số</th>
                <th>Lịch học</th>
                <th>Thời gian học còn lại</th>
                <th>Trạng thái</th>
            </tr>

        </table>
    </div>
</div>

<script>
    var table_view = document.querySelector('.view>table')
    var list_class = []
    loadTable()

    function loadTable() {
        let text = ''
        {% for cl in classes %}
        text += "<tr>"
        text += `<td><a href="" id="{{cl.id}}" class="aSlug">{{cl.slug}}</a></td>
            <td><a href="{% url 'detail_class' cl.id %}">{{cl.name}}</a></td>
            <td>{{cl.course}}</td>
            <td>{{cl.number_student}}/{{cl.number}}</td>
            <td>{{cl.get_day_display}}</td>
            <td>{{cl.duration}} week</td>
            <td>{{cl.get_status_display}}</td>
            `
        text += "</tr>"
        list_class.push({ "id": `{{cl.id}}`, "name": `{{cl.name}}`, 'slug': `{{cl.slug}}`, 'number': `{{cl.number}}`, 'schedule': `{{cl.day}}`, 'course': `{{cl.course.id}}` })
        {% endfor %}

        table_view.insertAdjacentHTML('beforeend', text)
    }

    document.querySelectorAll('.aSlug').forEach((item) => {
        item.addEventListener('click', (e) => {
            e.preventDefault()
            var slug = document.getElementsByName('slug')[0]
            var name = document.getElementsByName('name')[0]
            var number = document.getElementsByName('number')[0]
            var lichhoc = document.getElementsByName('schedule')[0]
            var khoahoc = document.getElementsByName('courses')[0]
            var iId = document.querySelector('#iId')

            let id = e.target.id
            for (let i of list_class) {
                if (i.id == id) {
                    slug.setAttribute('value', i.slug)
                    name.setAttribute('value', i.name)
                    number.setAttribute('value', i.number)
                    lichhoc.value = i.schedule
                    khoahoc.value = i.course
                    iId.setAttribute('value', i.id)
                }
            }
        })

    })
</script>
{% endblock contain %}

core/templates/core/course_view.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
Dashboard scheduling
{% endblock title %}

{% block head %}
<title>Course</title>
<link rel="stylesheet" href="{% static 'css/css/classes.css' %}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
{% endblock head %}

{% block contain %}
<div class="class-wrapper">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="text-center alert alert-{{ message.tags }} fade in alert-dismissible show"{% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" style="font-size:20px">&times;</span>
            </button>  
        {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <form name="formcourse" action="" method="post">
        {% csrf_token %}
        <h2 class="qllh">courses management</h2>

        <div class="form-group">
            <label for="">Tên khoá học:</label>
            <input type="text" name="name" required>
        </div>

        <div class="form-group">
            <label for="">Thời lượng:</label>
            <select name="duration" id="duration" required>
                <option disabled selected value>Thời lượng</option>
                <option value="3">3 Week</option>
                <option value="4">4 Week</option>
                <option value="5">5 Week</option>
                <option value="6">6 Week</option>
            </select>
        </div>

        <div class="form-group">
            <input type="submit" value="Thêm">
        </div>
    </form>

    <div class="view">
        <table class="custom-table">
            <tr class="tr-title">
                <th>ID</th>
                <th>Tên Khoá học</th>
                <th>Thời lượng</th>
                <th></th>
            </tr>

        </table>
    </div>


</div>

<script>
    var table_view = document.querySelector('.view>table')

    loadTable()

    function loadTable() {
        let text = ''
        {% for course in courses %}
        text += "<tr>"
        text += `<td><a href="#">{{course.id}}</a></td>
            <td>{{course.name}}</td>
            <td>{{course.get_duration_display}}</td>
            <td><a href="{% url 'deletecourses' course.id %}">Xoá</a></td>`
        text += "</tr>"
        {% endfor %}

        table_view.insertAdjacentHTML('beforeend', text)
    }
</script>
{% endblock contain %}

core/templates/core/detail_class.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
Dashboard scheduling
{% endblock title %}

{% block head %}
<title>Room</title>
<link rel="stylesheet" href="{% static 'css/css/classes.css' %}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
{% endblock head %}

{% block contain %}
<div class="class-wrapper">
    <h2>Chi tiết lớp</h2>
    <div class="view">
        <table class="custom-table">
            <tr class="tr-title">
                <th>Mã</th>
                <th>Tên</th>
                <th>Khoá học</th>
                <th>Buổi học</th>
                <th>Sĩ số</th>
            </tr>
            <tr>
                <td>{{class.slug}}</td>
                <td>{{class.name}}</td>
                <td>{{class.course}}</td>
                <td>{{class.get_day_display}}</td>
                <td>{{class.number_student}}/{{class.number}}</td>
            </tr>
        </table>
    </div>

    <h2>Danh sách học sinh</h2>

    <div class="view">
        <table class="custom-table">
            <tr class="tr-title">
                <th>ID</th>
                <th>Tên</th>
                <th>Ngày tháng năm sinh</th>
            </tr>

            {% for std in students %}
            <tr>
                <td>{{std.id}}</td>
                <td>{{std.name}}</td>
                <td>{{std.birth}}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>



{% endblock contain %}

core/templates/core/profile.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}
Profile
{% endblock title %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/css/classes.css' %}">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
{% endblock head %}

{% block contain %}
<div class="class-wrapper">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="text-center alert alert-{{ message.tags }} fade in alert-dismissible show"{% endif %}>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" style="font-size:20px">&times;</span>
            </button>  
        {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    <form name="" action="{% url 'updateprofile' %}" method="post">
        {% csrf_token %}
        <h2 class="qllh">student profile</h2>
        <div class="form-group">
            <label for="">Tên học sinh:</label>
            <input type="text" name="name" value="{{student.name}}">
        </div>
        <div class="form-group">
            <label for="">User Name:</label>
            <input type="text" name="phone" value="{{student.user.username}}" readonly>
        </div>
        <div class="form-group">
            <label for="">Ngày tháng năm sinh:</label>
            <input type="date" name="birth">
        </div>
        <div class="form-group">
            <label for="">Số điện thoại:</label>
            <input type="text" name="phone" value="{{student.phone}}">
        </div>

        <div class="form-submit">
            <input type="submit" value="Sửa">

        </div>
        
    </form>
    <h2>Danh sách các lớp đang học:</h2>
    <table class="table table-striped">
        <thead>
            <tr>
              <th>Class Name</th>
              <th>Course</th>
              <th>Duration</th>
              <th>Day</th>
            </tr>
          </thead>
          <tbody>
          {% for class in cls %}
              <tr>
                <td>{{class.name}}</td>
                <td>{{class.course}}</td>
                <td>{{class.duration}} weeks</td>
                <td>{{class.get_day_display}}</td>
              </tr>
          {% endfor %}
    </table>
</div>
<script>
    document.getElementsByName('birth')[0].value = `{{student.birth|date:"Y-m-d"}}`
</script>
{% endblock contain %}

core/templates/core/register.html
{% load static %}
<!DOCTYPE html>
<html>
    
<head>
	<title>My Awesome Login Page</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
</head>
<!--Coded with love by Mutiullah Samim-->
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<div class="brand_logo_container">
						<img src="https://cdn.freebiesupply.com/logos/large/2x/pinterest-circle-logo-png-transparent.png" class="brand_logo" alt="Logo">
					</div>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form action="" method="post">
                        {% csrf_token %}
                        {% comment %} <input type="hidden" name="next" value="/accounts/login"/> {% endcomment %}
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                            <input type="email" class="form-control input_user" placeholder="email" name="email" required="" id="id_email">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                            <input type="text" class="form-control input_user" placeholder="name" name="first_name" required="" id="id_first_name">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
                            <input type="text" class="form-control input_user" placeholder="username" name="username" maxlength="30" required="" id="id_username">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                            <input type="password" class="form-control input_password" placeholder="password" name="password1" required="" id="id_password1" aria-autocomplete="list">
						</div>

						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
                            <input type="password" class="form-control input_password" placeholder="repassword" name="password2" required="" id="id_password2">
						</div>

				
							<div class="d-flex justify-content-center mt-3 login_container">
				 	<button type="submit" name="button" class="btn login_btn">Sign Up</button>
				   </div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Do have an account? <a href="#" class="ml-2">Sign In</a>
					</div>
					
				</div>
			</div>
		</div>
	</div>
</body>
</html> 